# Generated by Django 5.2.6 on 2025-12-10 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('STOCK', '주식'), ('ETF', 'ETF')], default='STOCK', max_length=10)),
                ('market_type', models.CharField(max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('underlying_index', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('total_shares', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.BigIntegerField()),
                ('high_price', models.BigIntegerField()),
                ('low_price', models.BigIntegerField()),
                ('close_price', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
                ('nav', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_price', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
