# Generated by Django 5.2.6 on 2025-12-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='change',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='trading_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
