# Generated by Django 5.2.6 on 2025-12-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_dailyprice_change_dailyprice_trading_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='underlying_index',
        ),
    ]
