# Generated by Django 5.2.6 on 2025-12-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='fluctuation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
