# Generated by Django 5.2.6 on 2025-12-14 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_dailyprice_fluctuation_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chartprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('close_price', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_price', to='stocks.stock')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
