# Generated by Django 5.2.6 on 2025-12-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=30, null=True, unique=True, verbose_name="닉네임"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="프로필 이미지",
            ),
        ),
    ]
