# Generated by Django 5.2.6 on 2025-12-20 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="플랜명")),
                ("price", models.IntegerField(verbose_name="가격(원)")),
                (
                    "duration_days",
                    models.IntegerField(default=30, verbose_name="기간(일)"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "구독 플랜",
                "verbose_name_plural": "구독 플랜",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "구독중"),
                            ("cancelled", "취소됨"),
                            ("expired", "만료됨"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "billing_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="빌링키"
                    ),
                ),
                (
                    "customer_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="고객키"
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="구독 시작일")),
                ("expires_at", models.DateTimeField(verbose_name="구독 만료일")),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="취소일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.plan",
                        verbose_name="플랜",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "구독",
                "verbose_name_plural": "구독",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="결제금액")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                            ("refunded", "환불됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "payment_key",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="토스 결제키",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="주문번호"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="결제일시"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="subscriptions.subscription",
                        verbose_name="구독",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제",
                "verbose_name_plural": "결제",
                "ordering": ["-created_at"],
            },
        ),
    ]
