# Generated by Django 5.2.6 on 2025-12-22 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='종가')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='시가')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='고가')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='저가')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='거래량')),
            ],
            options={
                'verbose_name': '금 시세',
                'verbose_name_plural': '금 시세',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SilverPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('close_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='종가')),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='시가')),
                ('high_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='고가')),
                ('low_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='저가')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='거래량')),
            ],
            options={
                'verbose_name': '은 시세',
                'verbose_name_plural': '은 시세',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=20, verbose_name='금융회사 코드')),
                ('fin_prdt_cd', models.CharField(max_length=50, verbose_name='금융상품 코드')),
                ('kor_co_nm', models.CharField(max_length=100, verbose_name='금융회사명')),
                ('fin_prdt_nm', models.CharField(max_length=200, verbose_name='금융상품명')),
                ('product_type', models.CharField(choices=[('deposit', '정기예금'), ('saving', '적금')], default='deposit', max_length=20, verbose_name='상품유형')),
                ('join_way', models.TextField(blank=True, verbose_name='가입방법')),
                ('mtrt_int', models.TextField(blank=True, verbose_name='만기 후 이자율')),
                ('spcl_cnd', models.TextField(blank=True, verbose_name='우대조건')),
                ('join_deny', models.CharField(blank=True, max_length=10, verbose_name='가입제한')),
                ('join_member', models.TextField(blank=True, verbose_name='가입대상')),
                ('etc_note', models.TextField(blank=True, verbose_name='기타 유의사항')),
                ('max_limit', models.BigIntegerField(blank=True, null=True, verbose_name='최고한도')),
                ('dcls_strt_day', models.CharField(blank=True, max_length=10, verbose_name='공시 시작일')),
                ('dcls_end_day', models.CharField(blank=True, max_length=10, verbose_name='공시 종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '예적금 상품',
                'verbose_name_plural': '예적금 상품',
                'unique_together': {('fin_co_no', 'fin_prdt_cd')},
            },
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(choices=[('S', '단리'), ('M', '복리')], max_length=10, verbose_name='저축금리 유형')),
                ('intr_rate_type_nm', models.CharField(max_length=20, verbose_name='저축금리 유형명')),
                ('save_trm', models.IntegerField(verbose_name='저축기간(개월)')),
                ('intr_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='기본금리')),
                ('intr_rate2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='최고금리')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.depositproduct', verbose_name='상품')),
            ],
            options={
                'verbose_name': '예적금 옵션',
                'verbose_name_plural': '예적금 옵션',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.depositoption', verbose_name='선택 옵션')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='finance.depositproduct', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_products', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '가입 상품',
                'verbose_name_plural': '가입 상품',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
