# Generated by Django 5.2.6 on 2025-12-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='공시 종료일'),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='dcls_strt_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='공시 시작일'),
        ),
    ]
