# Generated by Django 5.2.6 on 2025-12-23 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAiRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_type', models.JSONField(default=dict, verbose_name='투자자 유형')),
                ('asset_allocation', models.JSONField(default=dict, verbose_name='자산 배분')),
                ('advice', models.JSONField(default=dict, verbose_name='조언')),
                ('recommended_deposit_ids', models.JSONField(default=list, verbose_name='추천 예적금 ID')),
                ('recommended_stock_ids', models.JSONField(default=list, verbose_name='추천 주식 ID')),
                ('deposit_recommendation', models.JSONField(default=dict, verbose_name='예적금 추천 정보')),
                ('stock_recommendation', models.JSONField(default=dict, verbose_name='주식 추천 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 추천 결과',
                'verbose_name_plural': 'AI 추천 결과',
            },
        ),
        migrations.CreateModel(
            name='UserFinanceSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings', models.BigIntegerField(default=0, verbose_name='입출금/저축')),
                ('investment', models.BigIntegerField(default=0, verbose_name='투자 자산')),
                ('income', models.BigIntegerField(default=0, verbose_name='연봉')),
                ('q2_goal', models.IntegerField(default=0, verbose_name='금융 목표')),
                ('q3_period', models.IntegerField(default=0, verbose_name='투자 기간')),
                ('q4_knowledge', models.IntegerField(default=0, verbose_name='금융 지식')),
                ('q5_experience', models.IntegerField(default=0, verbose_name='투자 경험')),
                ('q6_expected_return', models.IntegerField(default=0, verbose_name='기대 수익률')),
                ('q7_risk_tolerance', models.IntegerField(default=0, verbose_name='손실 감내')),
                ('q8_monthly_saving', models.IntegerField(default=0, verbose_name='월 저축 여력')),
                ('q9_loss_reaction', models.IntegerField(default=0, verbose_name='손실 시 반응')),
                ('q10_interest', models.IntegerField(default=0, verbose_name='관심 분야')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '금융 성향 설문',
                'verbose_name_plural': '금융 성향 설문',
            },
        ),
    ]
